
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const native = require('bindings')('native');
const fs = require('fs');
const path = require('path');

// get native address for Vulkan API 'const char*'
String.prototype.charAddress = function (isUtf16 = false) {
    return native.nativeAddress(this.toString(), isUtf16);
};

//
String.fromAddress = (address, length = 0)=> { return native.string(address, length); };
String.fromAddressUtf16 = (address, length = 0)=> { return native.stringUtf16(address, length); };

// 
Buffer.prototype.address = function () { return native.nativeAddress(this); }
Uint8Array.prototype.address = function () { return native.nativeAddress(this); }
Uint16Array.prototype.address = function () { return native.nativeAddress(this); }
Uint32Array.prototype.address = function () { return native.nativeAddress(this); }
BigInt64Array.prototype.address = function () { return native.nativeAddress(this); }
Int8Array.prototype.address = function () { return native.nativeAddress(this); }
Int16Array.prototype.address = function () { return native.nativeAddress(this); }
Int32Array.prototype.address = function () { return native.nativeAddress(this); }
BigUint64Array.prototype.address = function () { return native.nativeAddress(this); }
Float32Array.prototype.address = function () { return native.nativeAddress(this); }
Float64Array.prototype.address = function () { return native.nativeAddress(this); }
ArrayBuffer.prototype.address = function () { return native.nativeAddress(this); }
SharedArrayBuffer.prototype.address = function () { return native.nativeAddress(this); }
DataView.prototype.address = function () { return (native.nativeAddress(this.buffer) + BigInt(this.byteOffset)); }

// 
Buffer.fromAddress = native.buffer;
ArrayBuffer.fromAddress = native.arrayBuffer;
SharedArrayBuffer.fromAddress = native.arrayBuffer;

//
if (typeof exports != "undefined") { exports.nativeAddress = native.nativeAddress; }

// TODO: unified syntax!
const _glfwEnums = {};
_glfwEnums.GLFW_VERSION_MAJOR = 3;
_glfwEnums.GLFW_VERSION_MINOR = 3;
_glfwEnums.GLFW_VERSION_REVISION = 7;
_glfwEnums.GLFW_TRUE = 1;
_glfwEnums.GLFW_FALSE = 0;
_glfwEnums.GLFW_RELEASE = 0;
_glfwEnums.GLFW_PRESS = 1;
_glfwEnums.GLFW_REPEAT = 2;
_glfwEnums.GLFW_HAT_CENTERED = 0;
_glfwEnums.GLFW_HAT_UP = 1;
_glfwEnums.GLFW_HAT_RIGHT = 2;
_glfwEnums.GLFW_HAT_DOWN = 4;
_glfwEnums.GLFW_HAT_LEFT = 8;
_glfwEnums.GLFW_HAT_RIGHT_UP = _glfwEnums.GLFW_HAT_RIGHT | _glfwEnums.GLFW_HAT_UP;
_glfwEnums.GLFW_HAT_RIGHT_DOWN = _glfwEnums.GLFW_HAT_RIGHT | _glfwEnums.GLFW_HAT_DOWN;
_glfwEnums.GLFW_HAT_LEFT_UP = _glfwEnums.GLFW_HAT_LEFT | _glfwEnums.GLFW_HAT_UP;
_glfwEnums.GLFW_HAT_LEFT_DOWN = _glfwEnums.GLFW_HAT_LEFT | _glfwEnums.GLFW_HAT_DOWN;
_glfwEnums.GLFW_KEY_UNKNOWN = - 1;
_glfwEnums.GLFW_KEY_SPACE = 32;
_glfwEnums.GLFW_KEY_APOSTROPHE = 39;
_glfwEnums.GLFW_KEY_COMMA = 44;
_glfwEnums.GLFW_KEY_MINUS = 45;
_glfwEnums.GLFW_KEY_PERIOD = 46;
_glfwEnums.GLFW_KEY_SLASH = 47;
_glfwEnums.GLFW_KEY_0 = 48;
_glfwEnums.GLFW_KEY_1 = 49;
_glfwEnums.GLFW_KEY_2 = 50;
_glfwEnums.GLFW_KEY_3 = 51;
_glfwEnums.GLFW_KEY_4 = 52;
_glfwEnums.GLFW_KEY_5 = 53;
_glfwEnums.GLFW_KEY_6 = 54;
_glfwEnums.GLFW_KEY_7 = 55;
_glfwEnums.GLFW_KEY_8 = 56;
_glfwEnums.GLFW_KEY_9 = 57;
_glfwEnums.GLFW_KEY_SEMICOLON = 59;
_glfwEnums.GLFW_KEY_EQUAL = 61;
_glfwEnums.GLFW_KEY_A = 65;
_glfwEnums.GLFW_KEY_B = 66;
_glfwEnums.GLFW_KEY_C = 67;
_glfwEnums.GLFW_KEY_D = 68;
_glfwEnums.GLFW_KEY_E = 69;
_glfwEnums.GLFW_KEY_F = 70;
_glfwEnums.GLFW_KEY_G = 71;
_glfwEnums.GLFW_KEY_H = 72;
_glfwEnums.GLFW_KEY_I = 73;
_glfwEnums.GLFW_KEY_J = 74;
_glfwEnums.GLFW_KEY_K = 75;
_glfwEnums.GLFW_KEY_L = 76;
_glfwEnums.GLFW_KEY_M = 77;
_glfwEnums.GLFW_KEY_N = 78;
_glfwEnums.GLFW_KEY_O = 79;
_glfwEnums.GLFW_KEY_P = 80;
_glfwEnums.GLFW_KEY_Q = 81;
_glfwEnums.GLFW_KEY_R = 82;
_glfwEnums.GLFW_KEY_S = 83;
_glfwEnums.GLFW_KEY_T = 84;
_glfwEnums.GLFW_KEY_U = 85;
_glfwEnums.GLFW_KEY_V = 86;
_glfwEnums.GLFW_KEY_W = 87;
_glfwEnums.GLFW_KEY_X = 88;
_glfwEnums.GLFW_KEY_Y = 89;
_glfwEnums.GLFW_KEY_Z = 90;
_glfwEnums.GLFW_KEY_LEFT_BRACKET = 91;
_glfwEnums.GLFW_KEY_BACKSLASH = 92;
_glfwEnums.GLFW_KEY_RIGHT_BRACKET = 93;
_glfwEnums.GLFW_KEY_GRAVE_ACCENT = 96; 
_glfwEnums.GLFW_KEY_WORLD_1 = 161;
_glfwEnums.GLFW_KEY_WORLD_2 = 162;
_glfwEnums.GLFW_KEY_ESCAPE = 256;
_glfwEnums.GLFW_KEY_ENTER = 257;
_glfwEnums.GLFW_KEY_TAB = 258;
_glfwEnums.GLFW_KEY_BACKSPACE = 259;
_glfwEnums.GLFW_KEY_INSERT = 260;
_glfwEnums.GLFW_KEY_DELETE = 261;
_glfwEnums.GLFW_KEY_RIGHT = 262;
_glfwEnums.GLFW_KEY_LEFT = 263;
_glfwEnums.GLFW_KEY_DOWN = 264;
_glfwEnums.GLFW_KEY_UP = 265;
_glfwEnums.GLFW_KEY_PAGE_UP = 266;
_glfwEnums.GLFW_KEY_PAGE_DOWN = 267;
_glfwEnums.GLFW_KEY_HOME = 268;
_glfwEnums.GLFW_KEY_END = 269;
_glfwEnums.GLFW_KEY_CAPS_LOCK = 280;
_glfwEnums.GLFW_KEY_SCROLL_LOCK = 281;
_glfwEnums.GLFW_KEY_NUM_LOCK = 282;
_glfwEnums.GLFW_KEY_PRINT_SCREEN = 283;
_glfwEnums.GLFW_KEY_PAUSE = 284;
_glfwEnums.GLFW_KEY_F1 = 290;
_glfwEnums.GLFW_KEY_F2 = 291;
_glfwEnums.GLFW_KEY_F3 = 292;
_glfwEnums.GLFW_KEY_F4 = 293;
_glfwEnums.GLFW_KEY_F5 = 294;
_glfwEnums.GLFW_KEY_F6 = 295;
_glfwEnums.GLFW_KEY_F7 = 296;
_glfwEnums.GLFW_KEY_F8 = 297;
_glfwEnums.GLFW_KEY_F9 = 298;
_glfwEnums.GLFW_KEY_F10 = 299;
_glfwEnums.GLFW_KEY_F11 = 300;
_glfwEnums.GLFW_KEY_F12 = 301;
_glfwEnums.GLFW_KEY_F13 = 302;
_glfwEnums.GLFW_KEY_F14 = 303;
_glfwEnums.GLFW_KEY_F15 = 304;
_glfwEnums.GLFW_KEY_F16 = 305;
_glfwEnums.GLFW_KEY_F17 = 306;
_glfwEnums.GLFW_KEY_F18 = 307;
_glfwEnums.GLFW_KEY_F19 = 308;
_glfwEnums.GLFW_KEY_F20 = 309;
_glfwEnums.GLFW_KEY_F21 = 310;
_glfwEnums.GLFW_KEY_F22 = 311;
_glfwEnums.GLFW_KEY_F23 = 312;
_glfwEnums.GLFW_KEY_F24 = 313;
_glfwEnums.GLFW_KEY_F25 = 314;
_glfwEnums.GLFW_KEY_KP_0 = 320;
_glfwEnums.GLFW_KEY_KP_1 = 321;
_glfwEnums.GLFW_KEY_KP_2 = 322;
_glfwEnums.GLFW_KEY_KP_3 = 323;
_glfwEnums.GLFW_KEY_KP_4 = 324;
_glfwEnums.GLFW_KEY_KP_5 = 325;
_glfwEnums.GLFW_KEY_KP_6 = 326;
_glfwEnums.GLFW_KEY_KP_7 = 327;
_glfwEnums.GLFW_KEY_KP_8 = 328;
_glfwEnums.GLFW_KEY_KP_9 = 329;
_glfwEnums.GLFW_KEY_KP_DECIMAL = 330;
_glfwEnums.GLFW_KEY_KP_DIVIDE = 331;
_glfwEnums.GLFW_KEY_KP_MULTIPLY = 332;
_glfwEnums.GLFW_KEY_KP_SUBTRACT = 333;
_glfwEnums.GLFW_KEY_KP_ADD = 334;
_glfwEnums.GLFW_KEY_KP_ENTER = 335;
_glfwEnums.GLFW_KEY_KP_EQUAL = 336;
_glfwEnums.GLFW_KEY_LEFT_SHIFT = 340;
_glfwEnums.GLFW_KEY_LEFT_CONTROL = 341;
_glfwEnums.GLFW_KEY_LEFT_ALT = 342;
_glfwEnums.GLFW_KEY_LEFT_SUPER = 343;
_glfwEnums.GLFW_KEY_RIGHT_SHIFT = 344;
_glfwEnums.GLFW_KEY_RIGHT_CONTROL = 345;
_glfwEnums.GLFW_KEY_RIGHT_ALT = 346;
_glfwEnums.GLFW_KEY_RIGHT_SUPER = 347;
_glfwEnums.GLFW_KEY_MENU = 348;
_glfwEnums.GLFW_KEY_LAST = _glfwEnums.GLFW_KEY_MENU;
_glfwEnums.GLFW_MOD_SHIFT = 0x0001;
_glfwEnums.GLFW_MOD_CONTROL = 0x0002;
_glfwEnums.GLFW_MOD_ALT = 0x0004;
_glfwEnums.GLFW_MOD_SUPER = 0x0008;
_glfwEnums.GLFW_MOD_CAPS_LOCK = 0x0010;
_glfwEnums.GLFW_MOD_NUM_LOCK = 0x0020;
_glfwEnums.GLFW_MOUSE_BUTTON_1 = 0;
_glfwEnums.GLFW_MOUSE_BUTTON_2 = 1;
_glfwEnums.GLFW_MOUSE_BUTTON_3 = 2;
_glfwEnums.GLFW_MOUSE_BUTTON_4 = 3;
_glfwEnums.GLFW_MOUSE_BUTTON_5 = 4;
_glfwEnums.GLFW_MOUSE_BUTTON_6 = 5;
_glfwEnums.GLFW_MOUSE_BUTTON_7 = 6;
_glfwEnums.GLFW_MOUSE_BUTTON_8 = 7;
_glfwEnums.GLFW_MOUSE_BUTTON_LAST = _glfwEnums.GLFW_MOUSE_BUTTON_8;
_glfwEnums.GLFW_MOUSE_BUTTON_LEFT = _glfwEnums.GLFW_MOUSE_BUTTON_1;
_glfwEnums.GLFW_MOUSE_BUTTON_RIGHT = _glfwEnums.GLFW_MOUSE_BUTTON_2;
_glfwEnums.GLFW_MOUSE_BUTTON_MIDDLE = _glfwEnums.GLFW_MOUSE_BUTTON_3;
_glfwEnums.GLFW_JOYSTICK_1 = 0;
_glfwEnums.GLFW_JOYSTICK_2 = 1;
_glfwEnums.GLFW_JOYSTICK_3 = 2;
_glfwEnums.GLFW_JOYSTICK_4 = 3;
_glfwEnums.GLFW_JOYSTICK_5 = 4;
_glfwEnums.GLFW_JOYSTICK_6 = 5;
_glfwEnums.GLFW_JOYSTICK_7 = 6;
_glfwEnums.GLFW_JOYSTICK_8 = 7;
_glfwEnums.GLFW_JOYSTICK_9 = 8;
_glfwEnums.GLFW_JOYSTICK_10 = 9;
_glfwEnums.GLFW_JOYSTICK_11 = 10;
_glfwEnums.GLFW_JOYSTICK_12 = 11;
_glfwEnums.GLFW_JOYSTICK_13 = 12;
_glfwEnums.GLFW_JOYSTICK_14 = 13;
_glfwEnums.GLFW_JOYSTICK_15 = 14;
_glfwEnums.GLFW_JOYSTICK_16 = 15;
_glfwEnums.GLFW_JOYSTICK_LAST = _glfwEnums.GLFW_JOYSTICK_16;
_glfwEnums.GLFW_GAMEPAD_BUTTON_A = 0;
_glfwEnums.GLFW_GAMEPAD_BUTTON_B = 1;
_glfwEnums.GLFW_GAMEPAD_BUTTON_X = 2;
_glfwEnums.GLFW_GAMEPAD_BUTTON_Y = 3;
_glfwEnums.GLFW_GAMEPAD_BUTTON_LEFT_BUMPER = 4;
_glfwEnums.GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER = 5;
_glfwEnums.GLFW_GAMEPAD_BUTTON_BACK = 6;
_glfwEnums.GLFW_GAMEPAD_BUTTON_START = 7;
_glfwEnums.GLFW_GAMEPAD_BUTTON_GUIDE = 8;
_glfwEnums.GLFW_GAMEPAD_BUTTON_LEFT_THUMB = 9;
_glfwEnums.GLFW_GAMEPAD_BUTTON_RIGHT_THUMB = 10;
_glfwEnums.GLFW_GAMEPAD_BUTTON_DPAD_UP = 11;
_glfwEnums.GLFW_GAMEPAD_BUTTON_DPAD_RIGHT = 12;
_glfwEnums.GLFW_GAMEPAD_BUTTON_DPAD_DOWN = 13;
_glfwEnums.GLFW_GAMEPAD_BUTTON_DPAD_LEFT = 14;
_glfwEnums.GLFW_GAMEPAD_BUTTON_LAST = _glfwEnums.GLFW_GAMEPAD_BUTTON_DPAD_LEFT;
_glfwEnums.GLFW_GAMEPAD_BUTTON_CROSS = _glfwEnums.GLFW_GAMEPAD_BUTTON_A;
_glfwEnums.GLFW_GAMEPAD_BUTTON_CIRCLE = _glfwEnums.GLFW_GAMEPAD_BUTTON_B;
_glfwEnums.GLFW_GAMEPAD_BUTTON_SQUARE = _glfwEnums.GLFW_GAMEPAD_BUTTON_X;
_glfwEnums.GLFW_GAMEPAD_BUTTON_TRIANGLE = _glfwEnums.GLFW_GAMEPAD_BUTTON_Y;
_glfwEnums.GLFW_GAMEPAD_AXIS_LEFT_X = 0;
_glfwEnums.GLFW_GAMEPAD_AXIS_LEFT_Y = 1;
_glfwEnums.GLFW_GAMEPAD_AXIS_RIGHT_X = 2;
_glfwEnums.GLFW_GAMEPAD_AXIS_RIGHT_Y = 3;
_glfwEnums.GLFW_GAMEPAD_AXIS_LEFT_TRIGGER = 4;
_glfwEnums.GLFW_GAMEPAD_AXIS_RIGHT_TRIGGER = 5;
_glfwEnums.GLFW_GAMEPAD_AXIS_LAST = _glfwEnums.GLFW_GAMEPAD_AXIS_RIGHT_TRIGGER;
_glfwEnums.GLFW_NO_ERROR = 0;
_glfwEnums.GLFW_NOT_INITIALIZED = 0x00010001;
_glfwEnums.GLFW_NO_CURRENT_CONTEXT = 0x00010002;
_glfwEnums.GLFW_INVALID_ENUM = 0x00010003;
_glfwEnums.GLFW_INVALID_VALUE = 0x00010004;
_glfwEnums.GLFW_OUT_OF_MEMORY = 0x00010005;
_glfwEnums.GLFW_API_UNAVAILABLE = 0x00010006;
_glfwEnums.GLFW_VERSION_UNAVAILABLE = 0x00010007;
_glfwEnums.GLFW_PLATFORM_ERROR = 0x00010008;
_glfwEnums.GLFW_FORMAT_UNAVAILABLE = 0x00010009;
_glfwEnums.GLFW_NO_WINDOW_CONTEXT = 0x0001000A;
_glfwEnums.GLFW_FOCUSED = 0x00020001;
_glfwEnums.GLFW_ICONIFIED = 0x00020002;
_glfwEnums.GLFW_RESIZABLE = 0x00020003;
_glfwEnums.GLFW_VISIBLE = 0x00020004;
_glfwEnums.GLFW_DECORATED = 0x00020005;
_glfwEnums.GLFW_AUTO_ICONIFY = 0x00020006;
_glfwEnums.GLFW_FLOATING = 0x00020007;
_glfwEnums.GLFW_MAXIMIZED = 0x00020008;
_glfwEnums.GLFW_CENTER_CURSOR = 0x00020009;
_glfwEnums.GLFW_TRANSPARENT_FRAMEBUFFER = 0x0002000A;
_glfwEnums.GLFW_HOVERED = 0x0002000B;
_glfwEnums.GLFW_FOCUS_ON_SHOW = 0x0002000C;
_glfwEnums.GLFW_RED_BITS = 0x00021001;
_glfwEnums.GLFW_GREEN_BITS = 0x00021002;
_glfwEnums.GLFW_BLUE_BITS = 0x00021003;
_glfwEnums.GLFW_ALPHA_BITS = 0x00021004;
_glfwEnums.GLFW_DEPTH_BITS = 0x00021005;
_glfwEnums.GLFW_STENCIL_BITS = 0x00021006;
_glfwEnums.GLFW_ACCUM_RED_BITS = 0x00021007;
_glfwEnums.GLFW_ACCUM_GREEN_BITS = 0x00021008;
_glfwEnums.GLFW_ACCUM_BLUE_BITS = 0x00021009;
_glfwEnums.GLFW_ACCUM_ALPHA_BITS = 0x0002100A;
_glfwEnums.GLFW_AUX_BUFFERS = 0x0002100B;
_glfwEnums.GLFW_STEREO = 0x0002100C;
_glfwEnums.GLFW_SAMPLES = 0x0002100D;
_glfwEnums.GLFW_SRGB_CAPABLE = 0x0002100E;
_glfwEnums.GLFW_REFRESH_RATE = 0x0002100F;
_glfwEnums.GLFW_DOUBLEBUFFER = 0x00021010;
_glfwEnums.GLFW_CLIENT_API = 0x00022001;
_glfwEnums.GLFW_CONTEXT_VERSION_MAJOR = 0x00022002;
_glfwEnums.GLFW_CONTEXT_VERSION_MINOR = 0x00022003;
_glfwEnums.GLFW_CONTEXT_REVISION = 0x00022004;
_glfwEnums.GLFW_CONTEXT_ROBUSTNESS = 0x00022005;
_glfwEnums.GLFW_OPENGL_FORWARD_COMPAT = 0x00022006;
_glfwEnums.GLFW_OPENGL_DEBUG_CONTEXT = 0x00022007;
_glfwEnums.GLFW_OPENGL_PROFILE = 0x00022008;
_glfwEnums.GLFW_CONTEXT_RELEASE_BEHAVIOR = 0x00022009;
_glfwEnums.GLFW_CONTEXT_NO_ERROR = 0x0002200A;
_glfwEnums.GLFW_CONTEXT_CREATION_API = 0x0002200B;
_glfwEnums.GLFW_SCALE_TO_MONITOR = 0x0002200C;
_glfwEnums.GLFW_COCOA_RETINA_FRAMEBUFFER = 0x00023001;
_glfwEnums.GLFW_COCOA_FRAME_NAME = 0x00023002;
_glfwEnums.GLFW_COCOA_GRAPHICS_SWITCHING = 0x00023003;
_glfwEnums.GLFW_X11_CLASS_NAME = 0x00024001;
_glfwEnums.GLFW_X11_INSTANCE_NAME = 0x00024002;
_glfwEnums.GLFW_NO_API = 0;
_glfwEnums.GLFW_OPENGL_API = 0x00030001;
_glfwEnums.GLFW_OPENGL_ES_API = 0x00030002;
_glfwEnums.GLFW_NO_ROBUSTNESS = 0;
_glfwEnums.GLFW_NO_RESET_NOTIFICATION = 0x00031001;
_glfwEnums.GLFW_LOSE_CONTEXT_ON_RESET = 0x00031002;
_glfwEnums.GLFW_OPENGL_ANY_PROFILE = 0;
_glfwEnums.GLFW_OPENGL_CORE_PROFILE = 0x00032001;
_glfwEnums.GLFW_OPENGL_COMPAT_PROFILE = 0x00032002;
_glfwEnums.GLFW_CURSOR = 0x00033001;
_glfwEnums.GLFW_STICKY_KEYS = 0x00033002;
_glfwEnums.GLFW_STICKY_MOUSE_BUTTONS = 0x00033003;
_glfwEnums.GLFW_LOCK_KEY_MODS = 0x00033004;
_glfwEnums.GLFW_RAW_MOUSE_MOTION = 0x00033005;
_glfwEnums.GLFW_CURSOR_NORMAL = 0x00034001;
_glfwEnums.GLFW_CURSOR_HIDDEN = 0x00034002;
_glfwEnums.GLFW_CURSOR_DISABLED = 0x00034003;
_glfwEnums.GLFW_ANY_RELEASE_BEHAVIOR = 0;
_glfwEnums.GLFW_RELEASE_BEHAVIOR_FLUSH = 0x00035001;
_glfwEnums.GLFW_RELEASE_BEHAVIOR_NONE = 0x00035002;
_glfwEnums.GLFW_NATIVE_CONTEXT_API = 0x00036001;
_glfwEnums.GLFW_EGL_CONTEXT_API = 0x00036002;
_glfwEnums.GLFW_OSMESA_CONTEXT_API = 0x00036003;
_glfwEnums.GLFW_ARROW_CURSOR = 0x00036001;
_glfwEnums.GLFW_IBEAM_CURSOR = 0x00036002;
_glfwEnums.GLFW_CROSSHAIR_CURSOR = 0x00036003;
_glfwEnums.GLFW_HAND_CURSOR = 0x00036004;
_glfwEnums.GLFW_HRESIZE_CURSOR = 0x00036005;
_glfwEnums.GLFW_VRESIZE_CURSOR = 0x00036006;
_glfwEnums.GLFW_CONNECTED = 0x00040001;
_glfwEnums.GLFW_DISCONNECTED = 0x00040002;
_glfwEnums.GLFW_JOYSTICK_HAT_BUTTONS = 0x00050001;
_glfwEnums.GLFW_COCOA_CHDIR_RESOURCES = 0x00051001;
_glfwEnums.GLFW_COCOA_MENUBAR = 0x00051002;
_glfwEnums.GLFW_DONT_CARE = -1;

//
export default {
    ..._glfwEnums,
    ...native
}
